# Sponsor this project

github: # Add your GitHub username here
patreon: jamachi
ko_fi: jamachi
custom: [
  "https://buymeacoffee.com/jamachi",
  "https://fushionhubai.com.ng/support",
  "https://fushionhubai.com.ng/donate"
]